'use client';
import Link from 'next/link';
import {useCallback,useEffect,useState} from 'react';
import {Check,ChevronLeft,ChevronRight,CalendarDays,Stamp,Flame,Grid2X2,List,RefreshCw} from 'lucide-react';
import {koreaDay,currentStreak} from '../lib/attendance';
type RecordRow={day:string;created_at:string};
export default function Attendance({initialDay}:{initialDay:string}){
 const [records,setRecords]=useState<RecordRow[]>([]),[today,setToday]=useState(initialDay),[month,setMonth]=useState(initialDay.slice(0,7)),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[view,setView]=useState('calendar');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch('/api/attendance',{cache:'no-store',credentials:'same-origin'});const data=await r.json() as {error?:string;records:RecordRow[];today:string;alreadyChecked?:boolean};if(!r.ok)throw new Error(data.error);setRecords(data.records);setToday(data.today);setMonth(m=>m||data.today.slice(0,7));return true;}catch(e){setError(e instanceof Error?e.message:'기록을 불러오지 못했습니다.');return false;}finally{setLoading(false)}},[]);
 useEffect(()=>{void Promise.resolve().then(load)},[load]);
 useEffect(()=>{const sync=()=>{if(document.visibilityState==='visible')void load()};document.addEventListener('visibilitychange',sync);const timer=setInterval(()=>{if(koreaDay()!==today)void load()},30000);return()=>{document.removeEventListener('visibilitychange',sync);clearInterval(timer)}},[load,today]);
 const days=records.map(r=>r.day),checked=days.includes(today),monthDays=days.filter(d=>d.startsWith(month)),streak=today?currentStreak(days,today):0;
 async function checkIn(){setSaving(true);setMessage('');setError('');try{const r=await fetch('/api/attendance',{method:'POST',credentials:'same-origin'});const data=await r.json() as {error?:string;records:RecordRow[];today:string;alreadyChecked?:boolean};if(!r.ok)throw new Error(data.error);const refreshed=await load();setMonth(data.today.slice(0,7));if(refreshed)setMessage(data.alreadyChecked?'오늘은 이미 도장을 찍었어요.':'오늘의 도장을 찍었어요. 내일 또 만나요!');}catch(e){setError(e instanceof Error?e.message:'저장하지 못했습니다.')}finally{setSaving(false)}}
 function moveMonth(delta:number){const [y,m]=month.split('-').map(Number);const d=new Date(Date.UTC(y,m-1+delta,1));setMonth(d.toISOString().slice(0,7))}
 const [year,mon]=month.split('-').map(Number),first=month?new Date(Date.UTC(year,mon-1,1)).getUTCDay():0,count=month?new Date(Date.UTC(year,mon,0)).getUTCDate():0;
 return <><header><Link className="brand" href="/" aria-label="도장 홈"><span className="brand-mark"><Stamp size={22}/></span>도장<span className="brand-en">dozang</span></Link><div className="account"><span>나의 출석 수첩</span></div></header>
 <main><div className="intro"><p className="eyebrow">MY ATTENDANCE</p><h1>하루하루, 차곡차곡.</h1><p>작은 출석이 쌓여 나만의 기록이 됩니다.</p></div>
 <div className="workspace"><aside><section className="check-card"><div className="card-top"><span>오늘의 도장</span><span className="tag">하루 한 번</span></div><p className="today-date">{today?`${today.slice(0,4)}년 ${Number(today.slice(5,7))}월 ${Number(today.slice(8))}일`:'날짜 확인 중'}</p><div className={'big-stamp '+(checked?'is-checked':'')}><Stamp size={40} strokeWidth={1.4}/><strong>{checked?'출석 완료':'오늘도 출석'}</strong><span>{checked?'잘 오셨어요!':'지금 도장을 찍어 보세요'}</span></div><h2>{checked?'오늘의 한 칸을 채웠어요.':'오늘의 한 칸, 채워볼까요?'}</h2><p className="card-desc">{checked?'내일도 이곳에서 기다릴게요.':'버튼 한 번으로 오늘을 기록하세요.'}</p><button className="primary" disabled={loading||saving||checked||!!error} onClick={checkIn}>{checked?<Check size={19}/>:<Stamp size={19}/>} {saving?'도장 찍는 중…':loading?'기록 확인 중…':checked?'오늘 출석 완료':'출석체크'}</button><p className="timezone">한국 시간 자정에 새로운 하루가 시작돼요.</p></section>
 <section className="stats" aria-label="출석 통계"><div><span><Stamp size={17}/>누적 출석</span><strong>{loading?'—':records.length}<small>일</small></strong></div><div><span><Flame size={17}/>연속 출석</span><strong>{loading?'—':streak}<small>일</small></strong></div></section><div className="note"><CalendarDays size={20}/><p>로그인 없이, 바로 출석.<br/><span>이 브라우저의 쿠키로 내 수첩을 찾아요.<br/>쿠키 삭제·기기 변경 시 새로 시작해요.</span></p></div></aside>
 <section className="record-card"><div className="record-heading"><div><p className="eyebrow">STAMP COLLECTION</p><h2>나의 출석 기록</h2></div><div className="view-switch" aria-label="기록 보기 방식"><button aria-pressed={view==='calendar'} className={view==='calendar'?'active':''} onClick={()=>setView('calendar')}><Grid2X2 size={16}/>달력</button><button aria-pressed={view==='list'} className={view==='list'?'active':''} onClick={()=>setView('list')}><List size={16}/>전체 기록</button></div></div>
 {error&&<div className="error" role="alert">{error}<button onClick={()=>void load()}><RefreshCw size={15}/> 다시 불러오기</button></div>}<div className="sr-only" aria-live="polite">{message}</div>{message&&<p className="success">{message}</p>}
 {loading?<div className="empty">도장 기록을 불러오고 있어요…</div>:view==='calendar'?<><div className="month-nav"><h3>{year}년 {mon}월 <span>{monthDays.length}일 출석</span></h3><div><button onClick={()=>moveMonth(-1)} aria-label="이전 달"><ChevronLeft size={20}/></button><button className="this-month" onClick={()=>setMonth(today.slice(0,7))}>이번 달</button><button onClick={()=>moveMonth(1)} disabled={month>=today.slice(0,7)} aria-label="다음 달"><ChevronRight size={20}/></button></div></div><div className="calendar"><div className="weekdays">{['일','월','화','수','목','금','토'].map(d=><span key={d}>{d}</span>)}</div><div className="dates">{Array.from({length:first},(_,i)=><div key={'pad'+i} className="day blank"/>)}{Array.from({length:count},(_,i)=>{const day=`${month}-${String(i+1).padStart(2,'0')}`,done=days.includes(day),isToday=day===today;return <div key={day} className={'day '+(isToday?'today ':'')+(done?'done ':'')+(day>today?'future':'')} aria-label={`${day}${done?' 출석 완료':''}${isToday?' 오늘':''}`}><span className="day-number">{i+1}</span>{done?<span className="mini-stamp"><Check size={21}/><b>출석</b></span>:isToday?<span className="today-label">오늘</span>:<span className="day-dot"/>}</div>})}</div></div><div className="calendar-footer"><span><i/> 출석한 날</span><span>하나씩 채워지는 나의 한 달</span></div></>:<div className="history">{records.length===0?<div className="empty"><Stamp size={36}/><h3>아직 찍힌 도장이 없어요.</h3><p>오늘의 출석체크로 시작해 보세요.</p></div>:<><p className="history-total">지금까지 총 <b>{records.length}일</b> 출석했어요.</p><ul>{records.map(r=><li key={r.day}><span className="history-icon"><Check size={20}/></span><strong>{r.day.replaceAll('-','. ')}</strong><span>출석 완료</span><time>{new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit'}).format(new Date(r.created_at))}</time></li>)}</ul></>}</div>}
 </section></div></main><footer><span className="footer-logo">도장 <small>dozang</small></span><span>매일의 작은 기록.</span><span>Asia/Seoul · KST</span></footer></>
}
